- .github/workflows/pr-test.yml
- README.md
> [change] README.md

- model/model_test.go
- model/query.go
fix https://github.com/YaoApp/yao/issues/586
> Refactor query.go to improve alias handling in withHasOne function

- connector/database/xun.go
add the missing postgres dsn in gou
> add postgres dsn

- api/handler.go
in last pr, if the first non-space char is not `{`, then the json body will not parsed and return directly, but the body has not re-filled, fix the bug in this pr
> fix the bug introduced by last pr

- runtime/v8/objects/fs/fs.go
- runtime/v8/objects/fs/fs_test.go
…d corresponding tests for file retrieval
> Implement Download method in FS object

- model/url.go
- types/query.url.go
e.g. http://localhost:7001/api/model/search?pagesize=10&with=fields&fields.limit=300
fix the issue where fields.limit does not take effect
> url param: support with limit

- encoding/encoding.go
- encoding/json/json.go
- encoding/json_test.go
- go.mod
- go.sum
Introduces new JSON processing capabilities:
- Added `encoding.json.Repair` to fix malformed JSON
- Added `encoding.json.Parse` to parse JSON with automatic repair
- Updated dependencies to include jsonrepair library
- Expanded test coverage for new JSON processing methods
> Add JSON repair and parse functions to encoding package

- diff/diff.go
- diff/diff_test.go
- diff/process.go
- Implemented `Replace` method for text replacement using patch format
- Added `parsePatch` function to parse replacement patches
- Updated process handlers to support new replacement functionality
- Expanded test coverage for replacement methods
- Renamed some process methods for consistency (e.g., `diff.PatchApply` to `diff.Apply`)
> Add text replacement functionality to diff package

- plan/plan.go
- process/process.go
- runtime/v8/objects/plan/plan.go
- runtime/v8/objects/plan/plan_test.go
- runtime/v8/script.go
- runtime/v8/tests/plan_test.go
- Added `Release()` method to clean up plan resources
- Implemented `Trigger()` method for plan-wide event signaling
- Introduced `Exists()` method for process and script validation
- Updated V8 runtime Plan object with new methods:
* Run plan tasks
* Subscribe to task events
* Manage shared space
* Set and retrieve task data
- Expanded test coverage for plan execution and event handling
> Enhance Plan package with advanced task management and event handling

- runtime/v8/context.go
- Implemented `CallAnonymous()` method to execute anonymous JavaScript functions
- Added `CallAnonymousWith()` method supporting context-based anonymous function execution
- Used regex to remove function names and generate unique identifiers
- Supports compiling and running anonymous functions dynamically in V8 runtime
> Add anonymous function calling methods to V8 runtime context

- runtime/v8/bridge/bridge.go
- runtime/v8/context.go
- Implemented `WithGlobal()` method to add global variables to V8 context
- Added `Valuer` interface in bridge package for custom value conversion
- Enhanced JsValue function to support custom value interfaces
- Improved type handling for global variable setting in V8 context
> Add WithGlobal method to V8 runtime context and Valuer interface

- runtime/v8/objects/plan/plan.go
- Added support for custom task and subscribe function callbacks
- Implemented default task and subscribe functions with error handling
- Added Options struct to configure Plan object with custom callbacks
- Updated add and subscribe methods to support anonymous function sources
- Improved error handling and logging for task and subscribe operations
> Enhance Plan object with custom task and subscribe callbacks

- model/process.go
- model/process_test.go
- Implemented new model management processes: get, exists, reload, migrate, load, and unload
- Added corresponding test cases for each model management process
- Expanded model package functionality with detailed process handlers
- Registered new model management processes in the init function
> Add comprehensive model management processes and tests

- model/process.go
- plan/shared.go
Introduced Space interface for shared memory management with core operations (set/get/delete)
Implemented subscription/notification mechanisms for space interactions
Enhanced model retrieval with comprehensive metadata including name, description, and schema details
This PR establishes foundational memory management patterns while improving model information transparency.
> Add Space interface and enhance model metadata retrieval

- connector/connector.go
- connector/types.go
- Introduced `AIConnectors` variable to store AI connector options
- Enhanced `Load` function to append AI connector options based on DSL type
- Defined `Option` struct for labeling and value representation of connectors
- Improved organization of connector management with AI-specific handling
> Add AIConnectors support in connector package

- model/process.go
- model/process_test.go
- model/snap.go
- model/snap_test.go
- schema/types/types.go
- schema/xun/xun.go
- Implemented snapshot management processes: take, restore, drop, and check existence of snapshots
- Added test cases for each snapshot process to ensure functionality and error handling
- Enhanced the model process with new snapshot-related handlers in the process package
- Updated the schema to support temporary tables for snapshot management
> Add snapshot management processes and corresponding tests

- model/README.md
- model/atomic.go
- model/process.go
- model/process_test.go
- Implemented `Upsert` method in the model to create or update records based on unique identifiers.
- Added `MustUpsert` method for simplified usage that throws exceptions on errors.
- Enhanced process handling with a new `processUpsert` function to facilitate upsert operations.
- Developed comprehensive test cases for various scenarios of the upsert functionality, including validation of parameters and error handling.
- Updated the model process map to include the new upsert operation.
> Add Upsert functionality to model and corresponding tests

- helper/utils.go
- helper/utils_test.go
- Simplified the ToString function by removing unnecessary newline characters after each value.
- Enhanced error handling by ensuring error messages are not followed by newlines.
- Updated JSON marshaling to use jsoniter.MarshalIndent for better formatting of complex types.
- Improved overall readability and organization of the output string construction.
> Refactor ToString function in utils.go for improved output formatting

- runtime/v8/bridge/bridge.go
- Updated the JsError function to utilize exception.Trim for consistent error message formatting.
- Enhanced GoValue function to return native errors correctly.
- Added support for error type handling in JsValue function.
- Updated documentation comments to reflect changes in error handling behavior.
> Refactor error handling in V8 bridge for improved message clarity

- runtime/v8/objects/plan/plan.go
- runtime/v8/objects/plan/plan_test.go
- Implemented `getResults` method in the Plan object to retrieve task results after execution.
- Updated the `ExportObject` method to expose the new `Results` function.
- Added a new test case `TestPlanResults` to validate the retrieval of results for tasks in a plan.
- Enhanced error handling in the results retrieval process to ensure robustness.
> Add Results functionality to Plan object and corresponding tests

- runtime/v8/context.go
- runtime/v8/objects/plan/plan.go
- Improved error handling in the CallAnonymousWith method to display the source code when an error occurs during execution.
- Added line numbers to the output for better debugging and clarity.
- Updated error message in the plan execution to reflect more accurate terminology regarding plan execution failures.
> Enhance error reporting in V8 context execution

- graphrag/chunking/audio.go
- graphrag/chunking/csv.go
- graphrag/chunking/excel.go
- graphrag/chunking/semantic.go
- graphrag/chunking/structured.go
- graphrag/chunking/structured_test.go
- graphrag/chunking/video.go
- graphrag/tests/code.ts
- graphrag/types/interfaces.go
- graphrag/types/types.go
- Introduced the ChunkingFunction interface for handling text-to-chunk conversion, including methods for chunking text, files, and streams.
- Added new types: TextPosition and MediaPosition for representing position information in text and media content, respectively.
- Implemented the Chunk type to encapsulate content chunks with associated position information.
- Defined ChunkingOptions for customizable chunking behavior and ChunkingType enum for various content types.
- Established MIME type mappings to ChunkingType for improved content handling.
> Add chunking functionality and types for content processing

- graphrag/chunking/structured.go
- graphrag/chunking/structured_test.go
- Updated the leaf node detection logic to correctly calculate sub-size based on depth.
- Refactored the `TestNewFieldsHierarchy` to ensure index independence by creating a new chunker instance for each test.
- Improved index verification to ensure sequential indexing per depth level, enhancing test reliability.
- Introduced atomic counters for index generation in the `StructuredChunker`, allowing for concurrent index management.
> Refactor chunking tests and enhance index management

- graphrag/chunking/structured_test.go
- graphrag/cmd/main.go
- Introduced a new command-line flag for selecting chunking methods: structured, semantic, or both.
- Updated the main function to validate the selected method and adjust output directory creation accordingly.
- Implemented position mapping functionality to track chunk positions and save them in a JSON file for both structured and semantic chunking.
- Enhanced memory leak detection tests to provide more detailed logging and handle cases where memory allocation decreases.
> Enhance chunking process with method selection and position mapping

- graphrag/chunking/semantic.go
- graphrag/chunking/semantic_test.go
- Introduced `TestSemanticChunksConcurrentOrderAndIndex` to validate the order and index correctness of semantic chunks during concurrent processing.
- Added `TestSemanticChunksConcurrentStressTest` to stress test the concurrent processing of multiple structured chunks, ensuring proper handling under high load.
- Refactored the `processSemanticChunking` method to improve index management and maintain order during chunk processing.
- Enhanced error handling and logging for better traceability during tests.
> Add concurrent processing tests for semantic chunking

- graphrag/embedding/openai.go
- graphrag/embedding/openai_test.go
- Renamed and reorganized several test functions to improve clarity and consistency in testing direct POST requests.
- Enhanced error handling in tests to provide more informative logging for direct request scenarios.
- Removed the fallback method for direct requests, streamlining the embedding process to utilize direct POST requests exclusively.
- Updated the EmbedQuery method to reflect changes in request handling and improve error reporting.
> Refactor OpenAI embedding tests and update error handling

- graphrag/vector/qdrant/search.go
- graphrag/vector/qdrant/search_batch_test.go
- Enhanced the SearchBatch method to support concurrent execution of search options using goroutines and a semaphore for resource management.
- Added pre-validation for search options to ensure no nil values are processed, improving error handling.
- Refactored the search execution logic to handle multiple search types concurrently, optimizing performance and efficiency.
- Introduced a maximum concurrency limit to prevent resource exhaustion during search operations.
> Implement concurrent search execution in SearchBatch method

- graphrag/types/types.go
- graphrag/vector/qdrant/document.go
- graphrag/vector/qdrant/document_test.go
- graphrag/vector/qdrant/search.go
- graphrag/vector/qdrant/search_batch_test.go
- graphrag/vector/qdrant/search_hybrid_test.go
- graphrag/vector/qdrant/search_mmr_test.go
- graphrag/vector/qdrant/search_score_threshold_test.go
- graphrag/vector/qdrant/search_similar_test.go
- graphrag/vector/qdrant/search_test.go
- Refactored the Document struct to include new fields for DenseVector and SparseVector, improving support for various vector types.
- Introduced methods for checking the presence of dense and sparse vectors, enhancing the flexibility of vector operations.
- Updated AddDocumentOptions to include a VectorMode field, allowing for more granular control over vector handling during document addition.
- Enhanced search functionalities to accommodate named vectors, ensuring compatibility with both dense and sparse vector configurations.
- Updated tests to reflect changes in Document structure and vector handling, ensuring comprehensive coverage for new functionalities.
> Enhance Document and Vector handling in Qdrant integration

- graphrag/vector/qdrant/search_hybrid_test.go
- Adjusted indentation in the TestSearchHybrid_MultiLanguageSupport function to improve code readability.
- Ensured consistent handling of query vector checks, maintaining clarity in test logic for dense query vectors across multiple datasets.
> Refactor test structure for multi-language support in hybrid search

- graphrag/cmd/main.go
- Added a new command-line flag and method for clearing all collections from Qdrant, enhancing data management capabilities.
- Updated the method validation to include the new "clear-collections" option, ensuring proper handling of this functionality.
- Enhanced help documentation to reflect the new command usage for clearing collections.
- Implemented error handling and logging for the collection clearing process, providing feedback on success or failure.
> Implement clear-collections functionality in Qdrant integration

- graphrag/vector/qdrant/qdrant_evaluation_report_en.md
- Improved error handling across various methods to provide clearer feedback on failures and operational issues.
- Enhanced logging capabilities to capture detailed information during backup, restore, and collection operations, aiding in troubleshooting.
- Streamlined validation checks to ensure robustness in method execution, particularly for collection-related functionalities.
> Enhance error handling and logging in Qdrant integration

- graphrag/chunking/process.go
- graphrag/embedding/process.go
- graphrag/extraction/deepke.go
- graphrag/extraction/openai.go
- graphrag/extraction/process.go
- graphrag/extraction/spacy.go
- graphrag/types/interfaces.go
- graphrag/types/types.go
- Introduced new Extraction interface for handling document extraction processes, including methods for extracting documents and queries.
- Added ExtractionStatus and ExtractionPayload types to manage the status and context-specific data during extraction.
- Implemented ExtractionResults and ExtractionUsage types to encapsulate results and usage statistics from extraction operations.
- Enhanced the Chunking interface documentation for clarity and organization.
> Add extraction interfaces and related types for document processing

- graphrag/extraction/openai/openai_test.go
- Updated the memory usage calculation in the TestMemoryLeakDetection function to account for potential negative growth scenarios, ensuring accurate reporting of memory changes during tests.
- Added logic to differentiate between memory growth and decrease, enhancing the robustness of memory leak detection.
> Improve memory leak detection test to handle negative memory growth

- graphrag/utils/parser.go
- graphrag/utils/parser_test.go
- Introduced robust checks for incomplete JSON structures in the extraction parser, allowing for better handling of streaming data.
- Updated the `completeExtractionJSON` function to ensure required fields are present and to intelligently repair incomplete JSON.
- Added new methods for extracting valid entities and relationships from incomplete JSON, improving the overall reliability of the extraction process.
- Enhanced unit tests to cover various edge cases, ensuring accurate validation of JSON extraction logic.
> Enhance JSON extraction handling and testing

- graphrag/graph/neo4j/backup.go
- graphrag/graph/neo4j/connection.go
- graphrag/graph/neo4j/graph.go
- graphrag/graph/neo4j/neo4j.go
- graphrag/graph/neo4j/node.go
- graphrag/graph/neo4j/relationship.go
- graphrag/graph/neo4j/schema.go
- graphrag/graph/neo4j/stats.go
- graphrag/types/interfaces.go
- graphrag/types/types.go
- Removed deprecated VectorStoreFactory and GraphStoreFactory interfaces, consolidating functionality into more streamlined GraphStore and VectorStore interfaces.
- Introduced unified configuration structures for graph and vector stores, enhancing clarity and reducing redundancy.
- Updated node and relationship operations to support flexible options for adding, retrieving, and deleting entities in graph databases.
- Enhanced schema and index management capabilities, allowing for better integration with various graph database systems.
- Improved documentation and comments for better understanding of the new structures and their intended use.
> Refactor graph and vector store interfaces for improved consistency

- .github/workflows/pr-test.yml
- .github/workflows/unit-test.yml
- go.mod
- go.sum
- graphrag/graph/neo4j/connection.go
- graphrag/graph/neo4j/connection_test.go
- graphrag/graph/neo4j/graph.go
- graphrag/graph/neo4j/graph_test.go
- graphrag/graph/neo4j/neo4j.go
- graphrag/graph/neo4j/neo4j_test.go
- graphrag/graph/neo4j/test_utils.go
- Integrated the Neo4j Go driver to establish connections and manage graph databases.
- Implemented connection handling, including validation of required configurations and error handling for connectivity issues.
- Added methods for creating, dropping, and checking the existence of graphs, supporting both community and enterprise editions.
- Enhanced graph listing and description functionalities to provide detailed statistics about nodes and relationships.
- Updated GitHub workflows to include Neo4j testing environment configurations for improved CI/CD integration.
> Add Neo4j driver support and enhance graph management functionality

- graphrag/graph/neo4j/graph.go
- graphrag/graph/neo4j/graph_test.go
- graphrag/graph/neo4j/node.go
- graphrag/graph/neo4j/node_test.go
- graphrag/graph/neo4j/test_utils.go
- Updated graph name validation to allow dashes in addition to alphanumeric characters and underscores.
- Enhanced the CreateGraph method to return more informative error messages for invalid graph names.
- Implemented AddNodes method to facilitate batch addition of nodes, including validation and error handling.
- Introduced utility functions for loading and converting test graph data, improving test coverage and data management.
- Added comprehensive test cases for new functionalities to ensure robustness and reliability.
> Enhance graph name validation and add node management functionality

- graphrag/graph/neo4j/backup.go
- graphrag/graph/neo4j/backup_test.go
- graphrag/graph/neo4j/test_utils.go
- graphrag/types/types.go
- Added Backup and Restore methods to the Store struct, enabling graph backup and restoration in JSON and Cypher formats.
- Introduced BackupData struct to encapsulate backup metadata, nodes, and relationships.
- Implemented compression support for backup files using gzip.
- Enhanced error handling for various conditions, including connection status, graph existence, and data validation.
- Updated GraphBackupOptions and GraphRestoreOptions structs to include new fields for backup format and compression.
- Added utility functions for converting nodes and relationships to and from maps for backup and restoration processes.
- Introduced separate database stress test configuration to optimize performance in testing scenarios.
> Implement backup and restore functionality for Neo4j graphs

- graphrag/graph/neo4j/backup_test.go
- graphrag/graph/neo4j/neo4j_graphrag_evaluation_report.md
- graphrag/graph/neo4j/test_utils.go
- Introduced global cleanup function to remove existing test databases before running backup tests, ensuring a clean state.
- Updated test database naming to use shorter, timestamp-based names to avoid database limit issues.
- Enhanced error handling in restore tests to skip cases where database limits are reached, improving test reliability.
- Adjusted stress test configurations to lower success rate thresholds for separate database mode, accommodating database limitations.
> Enhance Neo4j backup tests with cleanup and improved naming conventions

- graphrag/graph/neo4j/backup.go
- graphrag/graph/neo4j/graph.go
- graphrag/graph/neo4j/neo4j_graphrag_evaluation_report.md
- graphrag/graph/neo4j/schema.go
- graphrag/graph/neo4j/schema_test.go
- graphrag/graph/neo4j/utils.go
- Introduced critical operation semaphore in index creation and deletion methods to prevent deadlocks and ensure serialized access.
- Updated benchmark tests for index creation and deletion to utilize separate database mode, enhancing performance and reliability.
- Improved error handling in benchmark tests for index operations, providing clearer feedback on failures.
- Enhanced test setup to ensure a clean state by deleting existing graphs before running benchmarks, improving test accuracy.
> Refactor Neo4j schema management with critical operation protection

- graphrag/types/types.go
- graphrag/utils/generate.go
- graphrag/utils/generate_test.go
- Introduced CollectionIDs struct to represent collection identifiers for vector, graph, and KV store databases.
- Enhanced type definitions in types.go to support better organization and management of database collections.
> Add CollectionIDs type for managing database collection identifiers

- graphrag/utils/generate.go
- graphrag/utils/generate_test.go
- runtime/v8/objects/store/README.md
- Replaced GenCollectionIDs with GetCollectionIDs and ValidateName functions to improve collection name validation and ID generation.
- Enhanced test coverage for collection name validation, ensuring proper error handling for invalid names.
- Updated documentation to reflect changes in collection ID generation methods and validation rules.
> Refactor collection ID generation and validation in utils

- .github/workflows/pr-test.yml
- .github/workflows/unit-test.yml
- ffmpeg/ffmpeg_test.go
- graphrag/collection_test.go
- Integrated FFmpeg setup in both GitHub Actions workflows (pr-test.yml and unit-test.yml) to ensure FFmpeg is available for testing.
- Added a test step to verify FFmpeg installation by checking its version.
- Refactored ffmpeg_test.go to improve test structure and coverage, including platform-specific tests and job management functionalities.
- Enhanced error handling and logging in tests to facilitate debugging and ensure robustness.
> Add FFmpeg setup to CI workflows and enhance ffmpeg_test.go

- .github/workflows/pr-test.yml
- .github/workflows/unit-test.yml
- Replaced the previous FFmpeg setup action with a custom installation script in both pr-test.yml and unit-test.yml workflows.
- The new approach downloads and installs FFmpeg 7.x directly, ensuring the latest version is used for testing.
- Updated permissions for the installed binaries to enhance execution capabilities.
> Refactor FFmpeg installation in CI workflows for improved reliability

- .github/workflows/pr-test.yml
- .github/workflows/unit-test.yml
- Changed the FFmpeg download source in both pr-test.yml and unit-test.yml workflows to use the latest release from GitHub, ensuring a more reliable and up-to-date installation.
- Updated the installation commands to reflect the new file structure of the downloaded package, maintaining the execution permissions for the installed binaries.
> Update FFmpeg installation method in CI workflows for consistency

- dns/dns.go
- mcp/client/client.go
- mcp/client/client_test.go
- mcp/client/connection.go
- mcp/client/connection_test.go
- mcp/client/initialization.go
- mcp/client/initialization_test.go
- mcp/client/resources.go
- mcp/client/transport.go
- mcp/client/utils_tests.go
- Updated error messages in the DNS resolution process for better clarity.
- Refactored the Client struct to include a pointer to the MCPClient for improved handling.
- Enhanced connection methods to accept context for better timeout management.
- Implemented graceful disconnect logic with timeout handling.
- Updated tests to reflect changes in connection setup and error handling, ensuring robustness in various scenarios.
> Refactor MCP client connection handling and improve error logging

- graphrag/README.md
- Improved error handling in the `Backup` and `Restore` methods to ensure robust logging of issues during backup and restoration processes.
- Refined utility functions for creating and extracting zip archives, enhancing reliability in the backup workflow.
- Updated tests to cover new error handling scenarios, ensuring comprehensive validation of backup and restore functionalities.
> Enhance backup and restore error handling and logging in GraphRag

- connector/connector.go
- connector/connector_test.go
- connector/types.go
- mcp/client/client_test.go
- mcp/client/utils_tests.go
- mcp/types/types.go
- Introduced `LoadSync` and `LoadSourceSync` functions to enable concurrent loading of connectors while ensuring thread safety using `RWMutex`.
- Added tests for loading multiple connectors concurrently, verifying successful loading and type assertions for each connector.
- Enhanced the `DSL` struct to incorporate `MetaInfo`, improving metadata handling for connectors.
- Updated existing tests to utilize the new structure and ensure comprehensive coverage of connector functionalities.
> feat: add concurrent loading of connectors with synchronization

- store/store.go
- store/types.go
- Introduced `LoadSync` and `LoadSourceSync` functions to enable thread-safe loading of stores using `RWMutex`.
- Updated the `Load` function to improve the loading process and ensure proper handling of store instances.
- Added a new `Get` function to retrieve stores from the pool, enhancing accessibility.
- Refactored the `Instance` struct to incorporate `types.MetaInfo`, improving metadata management.
- Organized imports in `types.go` for better readability.
> feat: enhance store loading with concurrency and synchronization

- graphrag/converter/video.go
- Introduced new fields in VideoOption for FFmpegPath, FFprobePath, EnableGPU, GPUIndex, and MaxThreads to enhance video processing configuration.
- Updated the NewVideo function to initialize FFmpeg with these new options, allowing for more flexible and customizable video processing setups.
> feat: add FFmpeg configuration options to VideoOption struct

- model/atomic.go
- model/model.go
- Updated the handling of unique columns in the LoadSource function to avoid duplicates by using a map for unique column storage.
- Modified the DeleteWhere and sqlite3DeleteWhere functions to generate unique timestamps for batch soft deletes, ensuring distinct values for each row.
- Improved code clarity with comments explaining the changes in timestamp generation logic.
> refactor: enhance unique column handling in model

- graphrag/vector/qdrant/connection.go
- graphrag/vector/qdrant/document.go
- Added a tryConnect method to handle automatic connection to the Qdrant server before adding documents.
- Improved error handling to ensure that connection failures are reported clearly.
- Updated the AddDocuments method to utilize the new connection logic, enhancing reliability when interacting with the Qdrant server.
> feat: implement auto-connection for Qdrant in AddDocuments method

- graphrag/vector/qdrant/document.go
- Updated the ScrollDocuments method to request limit+1 documents, allowing for better pagination handling.
- Improved the logic to determine if more results are available and adjusted the conversion of documents accordingly.
- Ensured that only the necessary documents are returned to the user while using the last document as a cursor for further scrolling.
> feat: enhance document scrolling logic in Qdrant

- graphrag/hit.go
- graphrag/score.go
- graphrag/segment.go
- graphrag/segment_test.go
- graphrag/store.go
- graphrag/vote.go
- graphrag/weight.go
- Refactored storage key formats for segments, votes, scores, and weights to incorporate docID, enhancing data organization and retrieval.
- Updated related methods to accommodate the new key formats, ensuring consistency across segment management operations.
- Improved error handling and logging for segment storage operations, providing better insights during execution.
> feat: update segment storage key formats to include docID

- go.mod
- graphrag/graph.go
- graphrag/graph/neo4j/save.go
- graphrag/graph/neo4j/save_test.go
- graphrag/types/interfaces.go
- graphrag/types/types.go
- Added GetSegmentRelationshipsByEntities method to retrieve all relationships connected to entities in a segment, improving data accessibility.
- Updated GetSegmentRelationships method to filter relationships based on segmentID in source_chunks, enhancing query precision.
- Introduced SaveExtractionResults method in the GraphStore interface to save extraction results and return actual saved data, streamlining data handling.
- Refactored SegmentExtractionResult structure to minimize data returned to frontend, focusing on statistical information only.
- Implemented setSourceInformation method to track source documents and chunks for extracted entities and relationships, ensuring better data provenance.
> feat: enhance segment relationship management and extraction processes

- graphrag/document.go
- graphrag/graph/neo4j/save.go
- graphrag/segment_add.go
- graphrag/segment_update.go
- Refactored AddFile, AddSegments, and UpdateSegments methods to utilize a unified extractAndStoreEntitiesAndRelationships function, improving code reuse and clarity.
- Updated error handling to provide more informative messages during entity and relationship extraction and storage.
- Enhanced SaveExtractionResults method to collect and return errors encountered during the saving process, ensuring better error reporting.
- Improved handling of embedding texts for entities and relationships, streamlining the process of preparing data for vector storage.
- Added validation for Neo4j property types to ensure compatibility during entity and relationship storage, enhancing data integrity.
> feat: enhance entity and relationship extraction and storage processes

- process/process.go
- process/types.go
- Introduced WithCallback method to set a callback function for the Process struct, enhancing its configurability.
- Added Callback field to the Process struct to store the callback function, allowing for custom processing behavior.
> feat: add callback functionality to Process struct
