YaoApp/gou

- .gitignore
- api.http.go
All other methods are uppercase, so `any` should be uppercase, and the the request method should not be mandatory.
> uppercase request method and ``.idea` fold add git ignore

- model/migrate.go
- model/model.go
1. fix typo gou/model/migrate.go to avoid panic when execute the yao restore.
2. add migrate option: do not insert values when migration, for in most cases I think, `yao restore` will insert the same records which contained in model dsl values, thus restore will fail.
> fix typo to avoid panic when execute yao restore

- api/handler.go
when content-type is application/json, now the `setPayload` will parse the body as `map[string]interface{}`, but if the body not a json object, but an array or just some simple type, then json unmarshal will be an error.
> avoid error when json body not object

- rag/driver/qdrant/engine.go
- rag/driver/qdrant/engine_test.go
- rag/driver/qdrant/file.go
- rag/driver/types.go
- rag/rag_test.go
- Refactored tests to use timestamp-based document IDs instead of UUIDs for better traceability
- Added new methods to RAG engine:
- `HasIndex()`: Check if an index exists
- `HasDocument()`: Verify document existence
- `GetMetadata()`: Retrieve document metadata
- Enhanced test coverage for new functionality
> RAG Engine Enhancements

- go.mod
- go.sum
This commit updates the hashicorp/yamux package to its latest minor version, ensuring the project uses the most recent compatible release of the library.
> Upgrade hashicorp/yamux dependency to version 0.1.2

- connector/openai/openai.go
This update introduces an optional Azure configuration parameter to the OpenAI connector, allowing users to specify Azure-specific settings. The changes include:
- Adding an 'Azure' field to the Options struct
- Updating environment variable resolution for the Azure parameter
- Incorporating Azure configuration in the connector's settings output
> Add Azure support to OpenAI connector configuration

- plan/plan.go
- plan/types.go
- runtime/v8/isolate.go
- runtime/v8/objects/plan/plan.go
- runtime/v8/objects/plan/plan_test.go
- Introduced `GetTaskStatus` method in Plan to retrieve status of a specific task
- Added `StatusUnknown` to task status constants for handling undefined task states
- Updated V8 runtime to include Plan object in isolate template
> Add task status retrieval and unknown status to Plan package

- runtime/v8/objects/plan/plan.go
- runtime/v8/objects/plan/plan_test.go
- Implemented `Get()` and `Set()` methods for Plan object to store and retrieve key-value data
- Added test case to verify Plan object's data storage and retrieval functionality
- Fixed argument passing in default task function to use processed arguments
> Add Get and Set methods to Plan object in V8 runtime

- .github/workflows/pr-receive.yml
- Upgraded actions/upload-artifact from v3 to v4
- Minimal change to improve GitHub Actions workflow compatibility
> Update GitHub Actions upload artifact to v4

- plan/shared.go
- runtime/v8/objects/plan/plan.go
- Replaced global `plans` map with `sync.Map` for concurrent access
- Updated all plan-related methods to use `sync.Map` Load, Store, and Delete operations
- Added type checking when loading plan instances
- Improved error handling for plan retrieval and management
- Removed direct map access in favor of thread-safe synchronization methods
> Refactor Plan object to use sync.Map for thread-safe plan management

- model/process.go
- model/process_test.go
- Implemented `processList` function to return loaded models
- Added support for optional metadata and columns retrieval
- Created test cases to verify model list functionality with different options
- Registered new "model.list" process in the model package
> Add model list process with optional metadata and columns retrieval

- runtime/v8/bridge/bridge.go
- Implemented `Unmarshal` function in V8 bridge package
- Enables easy conversion of JavaScript values to Golang structs using JSON marshaling
- Uses jsoniter for efficient JSON unmarshaling
- Complements existing `GoValue` and `goValueParse` methods for type conversion
> Add Unmarshal method for JavaScript to Golang value conversion

- model/process_test.go
- Updated test cases for the upsert functionality to include scenarios for creating and updating records with unique identifiers.
- Modified test data to reflect clearer naming conventions for upsert operations.
- Added assertions to verify the results of updates on existing records with specific columns.
> Enhance upsert tests in process_test.go

- .github/workflows/pr-test.yml
- .github/workflows/unit-test.yml
- Changed the Go version from 1.23.0 to 1.24 in both `pr-test.yml` and `unit-test.yml` workflows to ensure compatibility with the latest features and improvements.
> Update Go version in CI workflows to 1.24

- graphrag/chunking/structured.go
- graphrag/chunking/structured_test.go
- graphrag/types/types.go
- Added a `Leaf` field to the `Chunk` struct to indicate whether a chunk is a leaf node.
- Updated chunk generation methods to determine and set the `Leaf` status based on depth and size constraints.
- Enhanced existing tests to validate the correct marking of leaf nodes across various chunking scenarios.
- Refactored related functions to accept `ChunkingOptions`, allowing for more flexible chunking behavior.
> Implement leaf node detection in chunking process

- .gitignore
- graphrag/chunking/semantic.go
- graphrag/cmd/main.go
- graphrag/utils/utils.go
- Updated the `.gitignore` to exclude structured test files.
- Improved error handling in `callLLMForSegmentation` to manage empty or invalid `finalArguments` and `finalContent`, using fallback mechanisms when necessary.
- Enhanced `parseToolcallPositions` to include JSON repair as a last resort for parsing arguments.
- Refined `completeToolcallJSON` to ensure proper JSON structure for segments, adding checks for open braces and brackets, and improving handling of incomplete JSON structures.
> Enhance JSON handling in semantic chunking and utility functions

- .gitignore
- graphrag/chunking/semantic.go
- graphrag/chunking/semantic_test.go
- graphrag/cmd/main.go
- graphrag/types/chunk.go
- graphrag/types/chunk_test.go
- graphrag/types/types.go
- graphrag/utils/parser.go
- graphrag/utils/parser_test.go
- graphrag/utils/semantic.go
- graphrag/utils/semantic_test.go
- graphrag/utils/utils.go
- graphrag/utils/utils_test.go
- Updated the `.gitignore` to exclude additional command files related to semantic chunking.
- Refactored the `callLLMForSegmentation` method to accept chunk objects instead of raw text, improving clarity and functionality.
- Introduced a new `Position` struct to replace the deprecated `SemanticPosition`, streamlining position management.
- Enhanced the `processChunkSemanticSegmentation` method to prioritize semantic integrity during chunk creation.
- Improved error handling and validation in position parsing to ensure robustness against invalid inputs.
- Added tests for structured chunking integration to validate the new chunking process.
> Refactor semantic chunking and enhance position handling

- graphrag/converter/utf8_test.go
- Updated test cases in utf8_test.go to use shorthand byte slice notation for invalid UTF-8 sequences and empty slices, improving readability and consistency across tests.
> Refactor UTF-8 test cases for consistency

- Makefile
- Modified the TESTFOLDER variable in the Makefile to include 'office' in the list of packages for testing.
- This change ensures that tests related to the 'office' package are executed during the testing process.
> Update Makefile to include 'office' in test folder selection

- mcp/client/client.go
- mcp/client/connection.go
- mcp/client/connection_test.go
- mcp/client/initialization.go
- mcp/client/initialization_test.go
- mcp/client/transport.go
- mcp/client/utils_tests.go
- Added InitResult field to the Client struct to store the initialization response.
- Enhanced the Initialize method to store the result upon successful initialization.
- Updated Disconnect and Close methods to clear the initialization result.
- Introduced IsInitialized and GetInitResult methods for better state management.
- Expanded tests to verify initialization result storage and state transitions during connection lifecycle.
> Implement initialization result handling in MCP client

- .github/workflows/pr-test.yml
- .github/workflows/unit-test.yml
- Consolidated installation commands for pdftoppm, mutool, and imagemagick into a single line for efficiency.
- Updated version checking command for imagemagick from 'magick -version' to 'convert -version' for consistency across workflows.
> Update CI workflows to streamline installation of PDF tools

- Makefile
- model/types.go
- types/dsl.go
- Modified the `TESTFOLDER` variable in the Makefile to exclude additional directories for testing.
- Added `types.MetaInfo` to the `MetaData` struct in `types.go` to improve metadata handling in the model.
> fix: update test folder configuration and enhance model metadata

- connector/connector.go
- connector/database/xun.go
- connector/fastembed/fastembed.go
- connector/moapi/moapi.go
- connector/mongo/mongo.go
- connector/openai/openai.go
- connector/redis/redis.go
- connector/types.go
- graphrag/utils/utils_test.go
- mcp/client/client.go
- mcp/interfaces.go
- model/model.go
- Renamed the `make` function to `makeConnector` for clarity in connector creation.
- Added `GetMetaInfo` method to various connector types to enhance metadata retrieval.
- Updated the `Connector` interface to include the new `GetMetaInfo` method, ensuring consistency across implementations.
- Improved metadata handling in the model by introducing a `GetMetaInfo` method for better integration with the overall system.
> refactor: rename connector creation function and add GetMetaInfo method

- model/model.go
- Reintroduced the soft delete column in the LoadSource function, ensuring it is added when enabled.
- Added new permission columns for tracking created by, updated by, team ID, tenant ID, and public read/write permissions, enhancing the model's capability for access control.
- Improved code organization and clarity with comments detailing the new additions.
> feat: enhance model loading with soft delete and permission columns

- graphrag/segment.go
- graphrag/segment_test.go
- graphrag/types/interfaces.go
- graphrag/types/types.go
- graphrag/vector/qdrant/document.go
- graphrag/vector/qdrant/document_test.go
- Changed the BatchSize field to Limit in ScrollOptions and ScrollSegmentsOptions for consistency across the codebase.
- Updated related methods and tests to reflect this change, ensuring uniformity in pagination handling.
- Marked ListSegments and ListDocuments methods as deprecated to signal upcoming changes in their usage.
> refactor: update pagination options from BatchSize to Limit

- graphrag/segment.go
- graphrag/segment_test.go
- graphrag/store.go
- graphrag/store_test.go
- graphrag/types/interfaces.go
- Modified GetSegments, GetSegment, RemoveSegments, UpdateVote, UpdateScore, and UpdateWeight methods to accept a docID parameter, enhancing their functionality and ensuring proper document context during operations.
- Updated related tests to reflect these changes, ensuring comprehensive coverage for the new method signatures and error handling for empty docID cases.
- Removed the getDocIDFromExistingSegments function as it is no longer needed with the new approach.
> refactor: update segment management methods to include docID parameter

- graphrag/segment.go
- graphrag/utils/utils.go
- Updated the chunk creation process in convertSegmentTextsToChunks to preserve essential metadata from existing segments, including depth, index, leaf, and root properties.
- Introduced utility functions for safely extracting various data types from metadata, improving robustness and reducing potential errors during metadata handling.
- Ensured that the chunk structure is maintained while allowing for generic handling of other metadata fields.
> feat: enhance chunk creation with metadata preservation

- graphrag/document.go
- graphrag/segment.go
- graphrag/types/types.go
- Added support for user-defined metadata in the document storage process, allowing it to overwrite default metadata.
- Initialized chunk metadata in the chunk creation process, ensuring that metadata is consistently applied and accessible.
- Improved the overall structure of metadata handling within the GraphRag package, enhancing flexibility and robustness in document processing.
> feat: enhance chunk metadata handling in document processing

- graphrag/segment.go
- graphrag/types/interfaces.go
- graphrag/types/segment.go
- graphrag/types/types.go
- Introduced GetSegmentParents method to retrieve the parent tree of a given segment, enhancing hierarchical data access.
- Implemented buildSegmentTree method for recursive construction of segment parent trees based on metadata.
- Added utility methods for extracting parent IDs and depth from segment metadata, improving data handling.
- Enhanced SegmentTree struct with methods for determining root status and retrieving parent chains, facilitating better segment management.
> feat: add segment parent retrieval and tree structure management
